/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // GitHub color system
        'gh-canvas-default': 'var(--gh-canvas-default)',
        'gh-canvas-overlay': 'var(--gh-canvas-overlay)',
        'gh-canvas-inset': 'var(--gh-canvas-inset)',
        'gh-canvas-subtle': 'var(--gh-canvas-subtle)',
        'gh-border-default': 'var(--gh-border-default)',
        'gh-border-muted': 'var(--gh-border-muted)',
        'gh-border-emphasis': 'var(--gh-border-emphasis)',
        'gh-fg-default': 'var(--gh-fg-default)',
        'gh-fg-muted': 'var(--gh-fg-muted)',
        'gh-fg-subtle': 'var(--gh-fg-subtle)',
        'gh-accent-fg': 'var(--gh-accent-fg)',
        'gh-accent-emphasis': 'var(--gh-accent-emphasis)',
        'gh-accent-muted': 'var(--gh-accent-muted)',
        'gh-accent-subtle': 'var(--gh-accent-subtle)',
        'gh-success-fg': 'var(--gh-success-fg)',
        'gh-success-emphasis': 'var(--gh-success-emphasis)',
        'gh-success-muted': 'var(--gh-success-muted)',
        'gh-success-subtle': 'var(--gh-success-subtle)',
        'gh-attention-fg': 'var(--gh-attention-fg)',
        'gh-attention-emphasis': 'var(--gh-attention-emphasis)',
        'gh-attention-muted': 'var(--gh-attention-muted)',
        'gh-attention-subtle': 'var(--gh-attention-subtle)',
        'gh-severe-fg': 'var(--gh-severe-fg)',
        'gh-severe-emphasis': 'var(--gh-severe-emphasis)',
        'gh-severe-muted': 'var(--gh-severe-muted)',
        'gh-severe-subtle': 'var(--gh-severe-subtle)',
        'gh-danger-fg': 'var(--gh-danger-fg)',
        'gh-danger-emphasis': 'var(--gh-danger-emphasis)',
        'gh-danger-muted': 'var(--gh-danger-muted)',
        'gh-danger-subtle': 'var(--gh-danger-subtle)',
        'gh-open-fg': 'var(--gh-open-fg)',
        'gh-open-emphasis': 'var(--gh-open-emphasis)',
        'gh-open-muted': 'var(--gh-open-muted)',
        'gh-open-subtle': 'var(--gh-open-subtle)',
        'gh-closed-fg': 'var(--gh-closed-fg)',
        'gh-closed-emphasis': 'var(--gh-closed-emphasis)',
        'gh-closed-muted': 'var(--gh-closed-muted)',
        'gh-closed-subtle': 'var(--gh-closed-subtle)',
        'gh-done-fg': 'var(--gh-done-fg)',
        'gh-done-emphasis': 'var(--gh-done-emphasis)',
        'gh-done-muted': 'var(--gh-done-muted)',
        'gh-done-subtle': 'var(--gh-done-subtle)',
        'gh-sponsors-fg': 'var(--gh-sponsors-fg)',
        'gh-sponsors-emphasis': 'var(--gh-sponsors-emphasis)',
        'gh-sponsors-muted': 'var(--gh-sponsors-muted)',
        'gh-sponsors-subtle': 'var(--gh-sponsors-subtle)',
        'gh-primer-fg-disabled': 'var(--gh-primer-fg-disabled)',
        'gh-primer-canvas-backdrop': 'var(--gh-primer-canvas-backdrop)',
        'gh-primer-canvas-sticky': 'var(--gh-primer-canvas-sticky)',
        'gh-avatar-border': 'var(--gh-avatar-border)',
        'gh-topic-tag-border': 'var(--gh-topic-tag-border)',
        'gh-counter-border': 'var(--gh-counter-border)',
        'gh-select-menu-backdrop-border': 'var(--gh-select-menu-backdrop-border)',
        'gh-overlay-backdrop': 'var(--gh-overlay-backdrop)',
        'gh-header-text': 'var(--gh-header-text)',
        'gh-header-bg': 'var(--gh-header-bg)',
        'gh-header-divider': 'var(--gh-header-divider)',
        'gh-header-logo': 'var(--gh-header-logo)',
        'gh-footer-bg': 'var(--gh-footer-bg)',
        'gh-sidebar-bg': 'var(--gh-sidebar-bg)',
        'gh-timeline-badge-bg': 'var(--gh-timeline-badge-bg)',
        'gh-btn-text': 'var(--gh-btn-text)',
        'gh-btn-bg': 'var(--gh-btn-bg)',
        'gh-btn-border': 'var(--gh-btn-border)',
        'gh-btn-shadow': 'var(--gh-btn-shadow)',
        'gh-btn-inset-shadow': 'var(--gh-btn-inset-shadow)',
        'gh-btn-hover-bg': 'var(--gh-btn-hover-bg)',
        'gh-btn-hover-border': 'var(--gh-btn-hover-border)',
        'gh-btn-active-bg': 'var(--gh-btn-active-bg)',
        'gh-btn-active-border': 'var(--gh-btn-active-border)',
        'gh-btn-selected-bg': 'var(--gh-btn-selected-bg)',
        'gh-btn-primary-text': 'var(--gh-btn-primary-text)',
        'gh-btn-primary-bg': 'var(--gh-btn-primary-bg)',
        'gh-btn-primary-border': 'var(--gh-btn-primary-border)',
        'gh-btn-primary-shadow': 'var(--gh-btn-primary-shadow)',
        'gh-btn-primary-inset-shadow': 'var(--gh-btn-primary-inset-shadow)',
        'gh-btn-primary-hover-bg': 'var(--gh-btn-primary-hover-bg)',
        'gh-btn-primary-hover-border': 'var(--gh-btn-primary-hover-border)',
        'gh-btn-primary-selected-bg': 'var(--gh-btn-primary-selected-bg)',
        'gh-btn-primary-selected-shadow': 'var(--gh-btn-primary-selected-shadow)',
        'gh-btn-primary-disabled-text': 'var(--gh-btn-primary-disabled-text)',
        'gh-btn-primary-disabled-bg': 'var(--gh-btn-primary-disabled-bg)',
        'gh-btn-primary-disabled-border': 'var(--gh-btn-primary-disabled-border)',
        'gh-neutral-muted': 'var(--gh-neutral-muted)',
        'gh-neutral-subtle': 'var(--gh-neutral-subtle)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'bounce-subtle': 'bounceSubtle 0.6s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        bounceSubtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
      }
    },
  },
  plugins: [],
}
